package hello;


/**
* hello/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* vendredi 26 septembre 2025 09 h 36 WET
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
